{osConfig}: let
  inherit (osConfig.ooknet.appearance.colorscheme) palette;
in
  with palette;
  #css
    ''

      @define-color accent_color #${green};
      @define-color accent_bg_color #${text};
      @define-color accent_fg_color #${mantle};
      @define-color destructive_color #${blue};
      @define-color destructive_bg_color #${dull-blue};
      @define-color destructive_fg_color #${text};
      @define-color success_color #${cyan};
      @define-color success_bg_color #${green};
      @define-color success_fg_color #${text};
      @define-color warning_color #${yellow};
      @define-color warning_bg_color #${red};
      @define-color warning_fg_color #${text};
      @define-color error_color #${red};
      @define-color error_bg_color #${dull-red};
      @define-color error_fg_color #${text};
      @define-color window_bg_color #${crust};
      @define-color window_fg_color #${text};
      @define-color view_bg_color #${mantle};
      @define-color view_fg_color #${text};
      @define-color sidebar_bg_color #${crust};
      @define-color sidebar_fg_color #${text};
      @define-color sidebar_backdrop_color @window_bg_color;
      @define-color sidebar_shade_color rgba(0, 0, 0, 0.07);
      @define-color secondary_sidebar_bg_color @sidebar_bg_color;
      @define-color secondary_sidebar_fg_color @sidebar_fg_color;
      @define-color secondary_sidebar_backdrop_color @sidebar_backdrop_color;
      @define-color secondary_sidebar_shade_color @sidebar_shade_color;
      @define-color headerbar_bg_color #${base};
      @define-color headerbar_fg_color #${text};
      @define-color headerbar_border_color #${text};
      @define-color headerbar_backdrop_color @window_bg_color;
      @define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
      @define-color card_bg_color rgba(255, 255, 255, 0.08);
      @define-color card_fg_color #${text};
      @define-color card_shade_color rgba(0, 0, 0, 0.36);
      @define-color dialog_bg_color #${mantle};
      @define-color dialog_fg_color #${text};
      @define-color popover_bg_color #${mantle};
      @define-color popover_fg_color #${text};
      @define-color shade_color rgba(0,0,0,0.36);
      @define-color scrollbar_outline_color rgba(0,0,0,0.5);
      @define-color blue_1 #${blue};
      @define-color blue_2 #${blue};
      @define-color blue_3 #${blue};
      @define-color blue_4 #${blue};
      @define-color blue_5 #${blue};
      @define-color green_1 #b8bb26;
      @define-color green_2 #b8bb26;
      @define-color green_3 #b8bb26;
      @define-color green_4 #b8bb26;
      @define-color green_5 #b8bb26;
      @define-color yellow_1 #fabd2f;
      @define-color yellow_2 #fabd2f;
      @define-color yellow_3 #fabd2f;
      @define-color yellow_4 #fabd2f;
      @define-color yellow_5 #fabd2f;
      @define-color orange_1 #fe8019;
      @define-color orange_2 #fe8019;
      @define-color orange_3 #fe8019;
      @define-color orange_4 #fe8019;
      @define-color orange_5 #fe8019;
      @define-color red_1 #fb4934;
      @define-color red_2 #fb4934;
      @define-color red_3 #fb4934;
      @define-color red_4 #fb4934;
      @define-color red_5 #fb4934;
      @define-color purple_1 #d3869b;
      @define-color purple_2 #d3869b;
      @define-color purple_3 #d3869b;
      @define-color purple_4 #d3869b;
      @define-color purple_5 #d3869b;
      @define-color brown_1 #d65d0e;
      @define-color brown_2 #d65d0e;
      @define-color brown_3 #d65d0e;
      @define-color brown_4 #d65d0e;
      @define-color brown_5 #d65d0e;
      @define-color light_1 #${base05};
      @define-color light_2 #${base06};
      @define-color light_3 #${base07};
      @define-color light_4 #${base07};
      @define-color light_5 #${base07};
      @define-color dark_1 #${base00};
      @define-color dark_2 #${base01};
      @define-color dark_3 #${base02};
      @define-color dark_4 #${base03};
      @define-color dark_5 #${base04};
    ''
