name: "Build packages and push to cache"
on:
  workflow_dispatch:
  push:
    paths: 
      - outputs/pkgs/**
    branches:
      - main
concurrency:
  group: ooknet-cache-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - ook-vim
          - live-buds-cli
          - caddy-with-cloudflare
          - fpp-config
          - fpp-launcher
          - fpp-sd
          - project-plus
          - repomix
          - website
          - wii-u-gc-adapter
          - spotify-player
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: ooknet
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - name: Build packages
        run: nix build .#${{ matrix.package }} --print-build-logs
        continue-on-error: true
