name: "Nix Flake Check"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
concurrency:
  group: ooknet-check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run nixpkgs#alejandra -- --check .

  check-dead-code:
    name: Check Dead Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: deadnix
      - uses: astro/deadnix-action@main

  check-flake:
    name: Check Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KUNZEN_DEPLOY_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check

