name: "Nix Flake Check"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
concurrency:
  group: ooknet-check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  nix-flake-check:
    name: Check Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1 
        with:
          app-id: ${{ vars.APP_ID }}  # Updated input name
          private-key: ${{ secrets.APP_PRIVATE_KEY }}  # Updated input name
          repositories: 

      - name: Setup Git Config
        run: |
          git config --global url."https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/".insteadOf "git+ssh://git@github.com/"

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Nix Flake
        run: nix flake check
