name: "Nix Flake Check"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
concurrency:
  group: ooknet-check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  nix-flake-check:
    name: Check Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ooks-io
          repositories: kunzen

      - name: Setup Git Config
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "git+ssh://git@github.com/"

          git config --global --list

          git ls-remote https://github.com/ooks-io/kunzen.git
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Nix Flake
        run: nix flake check
