name: "Format Flake"
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .gitignore
jobs:
  alejandra:
    name: Format with Alejandra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Format Flake
        run: nix run nixpkgs#alejandra -- -c .
  deadnix:
    name: Dead Code Analysis with Deadnix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Deadnix
        uses: cachix/cachix-action@v15
        with: 
          name: deadnix
      - uses: astro/deadnix-action@main
